# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# https://ci.appveyor.com/project/holgern/pyedflib

# This file is built on the template here:
# http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      ARCHITECTURE: x86
    - PYTHON: "C:\\Python35-x64"
      ARCHITECTURE: x64
    - PYTHON: "C:\\Python36"
      ARCHITECTURE: x86
    - PYTHON: "C:\\Python36-x64"
      ARCHITECTURE: x64
    - PYTHON: "C:\\Python37"
      ARCHITECTURE: x86
    - PYTHON: "C:\\Python37-x64"
      ARCHITECTURE: x64
    - PYTHON: "C:\\Python38"
      ARCHITECTURE: x86
    - PYTHON: "C:\\Python38-x64"
      ARCHITECTURE: x64
    - PYTHON: "C:\\Python39"
      ARCHITECTURE: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: "C:\\Python39-x64"
      ARCHITECTURE: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build: off

install:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install --upgrade pip"
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install --upgrade wheel"
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe -m pip install
     Cython nose coverage matplotlib dateparser tqdm --cache-dir c:\\tmp\\pip-cache"

test_script:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe setup.py build --build-lib build\\lib\\"
  - "%PYTHON%\\Scripts\\nosetests build\\lib --tests pyedflib\\tests"

after_test:
  - "util\\appveyor\\build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

cache:
  # Cache can be manuall cleared like this:
  # https://github.com/appveyor/ci/issues/207
  - "c:\\tmp\\pip-cache"
